apiVersion: v1
kind: Service
metadata:
  name: somtranscriber-backend
  labels:
    app: somtranscriber-backend
spec:
  selector:
    app: somtranscriber-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
