apiVersion: v1
kind: Secret
metadata:
  name: somtranscriber-backend-secret
  labels:
    app: somtranscriber-backend
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:REPLACE_ME,iv:REPLACE_ME,tag:REPLACE_ME,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:REPLACE_ME,iv:REPLACE_ME,tag:REPLACE_ME,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:REPLACE_ME,iv:REPLACE_ME,tag:REPLACE_ME,type:str]
  BOOTSTRAP_USERNAME: ENC[AES256_GCM,data:REPLACE_ME,iv:REPLACE_ME,tag:REPLACE_ME,type:str]
  BOOTSTRAP_PIN: ENC[AES256_GCM,data:REPLACE_ME,iv:REPLACE_ME,tag:REPLACE_ME,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2026-02-10T00:00:00Z"
  mac: ENC[AES256_GCM,data:REPLACE_ME,iv:REPLACE_ME,tag:REPLACE_ME,type:str]
  pgp: []
  encrypted_regex: '^(data|stringData)$'
  version: 3.9.0
