apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend-configmap.yaml
  - backend-secret.sops.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-hpa.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - ollama-deployment.yaml
  - ollama-service.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
