apiVersion: v1
kind: Service
metadata:
  name: somtranscriber-ollama
  labels:
    app: somtranscriber-ollama
spec:
  selector:
    app: somtranscriber-ollama
  ports:
    - port: 11434
      targetPort: 11434
